language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl-dev
  - sudo apt-get install libsdl-image1.2-dev
  - sudo apt-get install libsdl-gfx1.2-dev
before_script:
  - mkdir build
  - cd build
  - cmake ../
script: make
