language: cpp

compiler:
  - gcc

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl-dev
  - sudo apt-get install -qq libsdl-image1.2-dev
  - sudo apt-get install -qq libsdl-gfx1.2-dev
  
before-script:
  - mkdir build
  - cd build
  - cmake ../
  
script: make
