language: cpp
compiler:
  - gcc
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libsdl1.2-dev
  - sudo apt-get -qq install libsdl-image1.2-dev
  - sudo apt-get -qq install libsdl-gfx1.2-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake ../
  
script: make -j 4

notifications:
  email:
    - albert@acervin.com
  irc:
    secure: "cw7F/yFI5YoGk+dzw0ykHe0t51BYvijUkHy3Dq890rmJT4p9f8zGJ2Rtq/+E/fUQvNpo9CH1vDJpJgRO1YGsWFYfJpNL4mzmWUFnNqSydMFweiihtwMX/UfQ2N+Od9wpIuYfABq9SKbPo5EXSAlyyr9rsWcAgV2qCa/Ffd4FqAk="
