language: cpp
compiler:
- gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install libsdl1.2-dev
- sudo apt-get -qq install libsdl-image1.2-dev
- sudo apt-get -qq install libsdl-gfx1.2-dev
before_script:
- mkdir build
- cd build
- cmake ../
script: make -j 4
notifications:
  email:
  - albert@acervin.com
  irc:
    channels:
      - secure: "o208yViAKSl6Q2aYiwvD4F3xUkkq6WdPiOCwTM34ZmRo9QA0CFl9Oy+X9zloYjfcVOc4Gkh8DKO0tKY2iw3JmdC/Ocs9sJTZUPEzmKDvCvHGSj7U0fhjZvNRkPwYGSIdn6IGEyHrIXfFniK1nG6t3WOhDaGKbJQN15q0G2mLG04="
    channel_key:
      secure: "osfV+EwGnL55R2CjWlBKdaEjNyUSFDNEx1ZCARjLK07fkcit123r/g9oZyO4mt1gGS/B+6Hm9mSOjMd1EVGJD+SQGQIYDLVC/9Nom3956uyroOGH7fH9PejrpmaizAzPvz4jHFd31k88r4QvrEqbyZHYgaPFZKvM1zBRf8FGC9Q="
